// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPp9cYmsrxQabuUXAL9cYlLX1YFFY7ZE',
    appId: '1:723468415897:web:5d39a4f91700409ea2d908',
    messagingSenderId: '723468415897',
    projectId: 'pro-grocery-app',
    authDomain: 'pro-grocery-app.firebaseapp.com',
    storageBucket: 'pro-grocery-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXKoYR2LKK6Ew0pjl9MR7D0QcPW2IuiLU',
    appId: '1:723468415897:android:b7cbec697c1ce009a2d908',
    messagingSenderId: '723468415897',
    projectId: 'pro-grocery-app',
    storageBucket: 'pro-grocery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF7XYby-1CX16wdEik1RP6_Svq2c9BoQQ',
    appId: '1:723468415897:ios:00ae829d12a69b48a2d908',
    messagingSenderId: '723468415897',
    projectId: 'pro-grocery-app',
    storageBucket: 'pro-grocery-app.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF7XYby-1CX16wdEik1RP6_Svq2c9BoQQ',
    appId: '1:723468415897:ios:00ae829d12a69b48a2d908',
    messagingSenderId: '723468415897',
    projectId: 'pro-grocery-app',
    storageBucket: 'pro-grocery-app.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADPp9cYmsrxQabuUXAL9cYlLX1YFFY7ZE',
    appId: '1:723468415897:web:79ec6e7fbc1b3edea2d908',
    messagingSenderId: '723468415897',
    projectId: 'pro-grocery-app',
    authDomain: 'pro-grocery-app.firebaseapp.com',
    storageBucket: 'pro-grocery-app.firebasestorage.app',
  );
}
