type User @table {
  displayName: String!
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  shippingAddress: String
  billingAddress: String
  phoneNumber: String
}

type Category @table {
  name: String!
  createdAt: Timestamp!
  description: String
}

type Product @table {
  name: String!
  description: String!
  price: Float!
  stock: Int!
  category: Category!
  createdAt: Timestamp!
  imageUrl: String
  weight: Float
  dimensions: String
}

type CartItem @table(key: ["user", "product"]) {
  user: User!
  product: Product!
  quantity: Int!
  createdAt: Timestamp!
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  shippingAddress: String!
  status: String!
  createdAt: Timestamp!
  billingAddress: String
  paymentMethod: String
}

type OrderItem @table(key: ["order", "product"]) {
  order: Order!
  product: Product!
  quantity: Int!
  priceAtTimeOfPurchase: Float!
}